public class practice {

    static integer i = 10;
    static integer u =20;
    
    public static void condition(){
        if (i<u){
            system.debug('+u');
        system.debug('+u');
        }
        else 
            system.debug('+i');
    }

    public static void condition1(){        
        integer i = 10;
        switch on i {
            when 10{
                system.debug('hi this prasantj');
            }
            when 12{
                system.debug('hi this is 12');
            }
            
        }
        }
        
    public static void whilec(){
        integer i =12;
        integer u= 14;
        while (i<u){
            system.debug('this is correct');
            
        }
    }
    public static void dowhi(){
        integer e =13;
        integer t =14;
        do{
            system.debug('hi this is sample');
           }while(e<t)      ;    
    }
    
    
 }